---
apiVersion: v1
kind: Service
metadata:
  name: bakery-app-starter-flow-spring-service
spec:
  ports:
  - name: http
    port: 8000
    protocol: TCP
    targetPort: 8080
  type: LoadBalancer
  sessionAffinity: ClientIP
