---
spec:
  replicas: 4
  template:
    spec:
      containers:
      - env:
        - name: JAVA_OPTIONS
          value: "-Xmx512M"
        resources:
          limits:
            memory: 512Mi
          requests:
            memory: 256Mi
