---
spec:
  replicas: 4
  template:
    spec:
      containers:
      - env:
        - name: SPRING_DATASOURCE_DRIVERCLASSNAME
          value: org.postgresql.Driver
        - name: SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT
          value: org.hibernate.dialect.PostgreSQLDialect
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:postgresql://bakery-database:5432/bakery"
        - name: SPRING_JPA_HIBERNATE_DDLAUTO
          value: update
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            configMapKeyRef:
              name: bakery-database-config
              key: postgres_user
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: bakery-database-config
              key: postgres_password
