name: Flow Validation
on:
  push:
    branches: [v23]
  workflow_dispatch:
  pull_request_target:
    types: [opened, synchronize, reopened]
jobs:
  build:
    timeout-minutes: 20
    runs-on: ubuntu-latest
    steps:
      - uses: actions-cool/check-user-permission@v2
        id: check
        with:
          require: 'write'
      - name: Check Secrets
        run: |
          if [ "${{ steps.check.outputs.require-result }}" != "true" ]; then
            echo "::error::!! NO USER PERMISSIONS FOR RUNNING VALIDATION: Check if the PR is from an external contributor !!"
            exit 1
          fi
          if [ -z "${{secrets.TB_LICENSE}}" ]; then
            echo "::error::!! ERROR NO TB_LICENSE: Check that this repo has a valid TB_LICENSE secret !!"
            exit 1
          fi
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Set TB License
        run: |
          TBL=${{secrets.TB_LICENSE}}
          mkdir -p ~/.vaadin/
          echo '{"username":"'`echo $TBL | cut -d / -f1`'","proKey":"'`echo $TBL | cut -d / -f2`'"}' > ~/.vaadin/proKey          
      - uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-
      - uses: browser-actions/setup-chrome@latest
        with:
          chrome-version: stable
      - uses: nanasess/setup-chromedriver@master          
      - name: Verify
        run: |
          mvn -B -V -ntp verify -Pit,production
      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        with:
          files: "**/target/*-reports/TEST*.xml"
          check_run_annotations: all tests, skipped tests
          check_run_annotations_branch: v23
